### ISSUE TITLE
Basque (eu) flag missing

### ISSUE THREAD

**Issue by urtzai** [popcorn-official/popcorn-site-legacy#26]
I'm not gimp/photoshop expert so... can someone help me to create a flag? Here is a sample http://cala.unex.es/cala/epistemowikia/images/1/17/Ikurri%C3%B1a.png

**Comment by sharkiller** [comment]
already added https://github.com/popcorn-official/popcorn-site/blob/master/images/flags/eu.png

**Comment by urtzai** [comment]
Thank you!
