### ISSUE TITLE
Font that supports all languages' character sets

### ISSUE THREAD

**Issue by berdesos** [popcorn-official/popcorn-site-legacy#31]
Currently, the chosen font (BrandonText) does not support the bulgarian and the greek characters of the related versions of the website.

It would be wise if you could use a more universal font such as HelveticaNeue, Arial or something from Google Web Fonts (like Roboto, Roboto Condensed), so the website to have a uniform appearance in all languages.

Especially Roboto Condensed supports pretty much all character sets and it looks very good as well: http://www.google.com/fonts/specimen/Roboto+Condensed

**Comment by fxbt** [comment]
There is a lot of difference between Roboto Condensed and Brandon.

To stay the closest to the current design, i suggest to use Open Sans instead. It's a Google Font as well.

https://www.google.com/fonts/specimen/Open+Sans

**Brandon**
![image](https://cloud.githubusercontent.com/assets/6928162/2762607/9a93fdda-c9f4-11e3-80b5-60a19f1ca2c1.png)

**Open Sans**
![image](https://cloud.githubusercontent.com/assets/6928162/2762615/bce121ba-c9f4-11e3-9efa-15765cf73285.png)

**Comment by berdesos** [comment]
Yes thats true. If you want to stay close to the original design then Open Sans is pretty much the best solution. However Roboto Condensed might look better (it's a matter of personal taste). Let me know which you prefer and I can make a pull request with Open Sans

<strong>Roboto Condensed</strong>
![screen shot](https://cloud.githubusercontent.com/assets/4678437/2763633/7ea5a99a-ca06-11e3-9c28-0d61ced929da.png)

**Comment by berdesos** [comment]
Done!

**Comment by the4dpatrick** [comment]
Shouldn't this issue be closed?

**Comment by berdesos** [comment]
I don't know. Should it? Right now there are not any other languages in the website and Proxima Nova font does not support all chars. Do you think then that the issue is solved? If English is the only language from now on, then yes the problem is solved!

Before the current version I had 2 friends that when they saw the fact the greek chars were inconsistent with the rest of the website's font, though that this version of popcorn time was a scam and they download time4popcorn!!!

**Comment by ghost** [comment]
@berdesos We don't support Greek language, nor did we before! This is closed as we are trying to maintain a consistent style across everything we do.

**Comment by berdesos** [comment]
Of course you did support Greek language. I should know because I translated the main part of Modern Greek in https://www.getlocalization.com/PopcornTime/

A consistent style only in English is a wise choice...

**Comment by ghost** [comment]
@berdesos Translations is coming. Its very busy behind the scenes at the moment. When things calm down a little, we will get to this!

**Comment by berdesos** [comment]
In my opinion local translation is useless. English is a universal language and you have very few words/sentences in general, most of them being English/computer terms thus difficult to translate (e.g. torrents). I think it would be better to focus on the app & the functionality of the website.
