### ISSUE TITLE
Spanish translation is Argentina-specific

### ISSUE THREAD

**Issue by fitojb** [popcorn-official/popcorn-site-legacy#35]
… and it is marked with the Spain flag, which is wrong. Unless you want to add multiple Spanish dialects, please fix the existing translation to remove Argentina-specific forms and slang (what’s “pochoclo”?), make it neutral, and remove the Spanish flag (use a symbol with no country connotation, such as an “Ñ”).

**Comment by fxbt** [comment]
For translation issues, please use http://getlocalization.com/PopcornTime/

**Comment by leandrosalo** [comment]
Where is the respect to the originals makers???

**Comment by fitojb** [comment]
@Saleitor Don’t be so th(d)ick. Honestly.

ALL I REPORTED is that the translation uses Argentinian slang but is marked with a Spain flag, which is wrong. I did not say anything else, nor I “disrespected” Argentinians.

cc / @foxbot

**Comment by xaiki** [comment]
So is it OK to rename this no: 'transation should have argentinian flag' ?

**Comment by fitojb** [comment]
@xaiki Yes, why not? I’m glad someone understood what I meant, instead of redirecting me t another site or attacking me.

**Comment by sharkiller** [comment]
Is still Spanish and you understand it. Pochoclo is not a slang and popcorn have a lot of translations (palomitas de maíz, alborotos, millo, rositas de maíz, gallitos, poporopos, poscon, popcon, pocorn, poporochos, pochoclos, pururú, pop, popcorn, pop corn, canchita, cancha perlita, canguil, pororó, cotufas, crispetas, maíz pira, chivitas, cabritas de maíz, maíz tote, pipocas, rosetas, rosas, rositas, roscas, tostones, cocaleca, o flores), and based the app was created in Argentina and the mascot is called "Pochoclin" I don't see anything wrong.

**Comment by fitojb** [comment]
@Sharkiller A ver si en español me entienden. JAMÁS DIJE QUE EL HABLA ARGENTINA ESTUVIERA MAL. Lo que es incorrecto es que le pongan una bandera de España. Eso es todo lo que estoy pidiendo que se cambie al abrir este informe. ¿Ya me hice entender? Carajo.

**Comment by sharkiller** [comment]
El uso de la bandera de España es prácticamente el estándar para referirse al idioma español y cualquier persona hispanohablante lo deduce al instante. Ya se te contestó porque se dejó la traducción como pochoclo. La bandera no se va a cambiar y a ver si bajamos un poco los humos.

**Comment by leandrosalo** [comment]
Reconozco que me enoje de mas... pasa que desde que se cerro el proyecto original y salieron estas continuaciones no hay nada ( notable ) que diga "estas personas fueron las creadoras"...

Como dice @sharkiller ... La bandera de España es la reconocible mundialmente ( aunque en Argentina se habla Castellano y no Español ), o la de México ( que ahí si, es como decir: español neutro ).

Para mi debería quedar lo de "pochoclo", y la bandera de España/México/Argentina ( no me siento ofendido sea cual sea ).

De vuelta me disculpo, no tengo un gran vocabulario Ingles, no siempre me puedo expresar como yo en realidad quiero en ese idioma. @Fitoschido  perdón por llevarte al enojo.

**Comment by fitojb** [comment]
@sharkiller No te respondo más que un «WTF?» El cerrado con los humos arriba aquí no soy yo, ¿eh?

@Saleitor Te agradezco infinitamente tu amable respuesta. Concuerdo completamente con tu opinión sobre el término «pochoclo» (yo, por encima de todo, abogo por la diversidad de la lengua… no por nada estudio letras hispánicas :) ), y también me gusta tu sugerencia de las banderas. Y no te preocupes, yo también reaccioné inadecuadamente ;)
Por cierto: si puedo hacer algo más para que esta continuación del proyecto siga, yo soy el primer interesado. No sé programar mucho, pero espero contribuir con algo útil en el futuro.

Saludos a todos.
