### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by Coleyra** [popcorn-official/popcorn-site-legacy#4]
Since popcorn-time is already translated in multiple languages, the website need to be translated too.

**Comment by SrPatinhas** [comment]
@sammuel86 i was the last one to change the web site, @Coleyra if you want i can update the site and make some of the translations

**Comment by Coleyra** [comment]
Well, we need to think of long term. We can't change every translation each time we modify the main one.

We should base the work with a mechanism of translation like on the main app. So we need to use a dynamic language like PHP for example.

**Comment by SrPatinhas** [comment]
I have some experience with it, I'm web developer and work with php and other languages​​, I can do something for this, but would only be in php or several pages and would be better with the base and then several languages ​​in jquery?

**Comment by Coleyra** [comment]
Well i'm a PHP web dev too, so we can work together to make something good and persistent.
I don't think that translating page with JS is a good idea, we should probably go with something like PHP and gettext.

BTW i'm french so i can easily translate the site in french.

**Comment by SrPatinhas** [comment]
yes, it can be that to

**Comment by Coleyra** [comment]
Well, i don't know what's the best way to do it in an open source project :)
Do we need some naming standard, or something like that ?

**Comment by phnz** [comment]
I suggest using PHP + poeditor.com for translation on the frontend we dont have more than 1k strings so we can use the free version.

**Comment by phnz** [comment]
We can also use http://i18next.com

**Comment by Coleyra** [comment]
PHP + poeditor.com is a good thing i think.

But my question was, if we want to translate the title of the page, how do we do ?

<hr />

Initial code #1 (from Homepage) :
&lt;title>Popcorn Time - Watch torrent movies instantly&lt;/title>

Method #1 : 
&lt;title><?php echo _('Popcorn Time - Watch torrent movies instantly'); ?>&lt;/title>

Method #2 : 
&lt;title><?php echo _('home-title'); ?>&lt;/title>

<hr />

Initial Code #2 (from FAQ) : 
&lt;article id="update">
                &lt;h2>Will there be a new version?&lt;/h2>
                &lt;p>Most definitely. You're going to have to download it manually though. But fear not! If you're on version Beta 2, you'll be notified within the app. Other than that, we'll let you know through Facebook and/or Twitter.&lt;/p>
            &lt;/article>

Method #1 : 
&lt;article id="update">
                &lt;h2><?php echo ('Will there be a new version'); ?>?&lt;/h2>
                &lt;p><?php echo "Most definitely. You're going to have to download it manually though. But fear not! If you're on version Beta 2, you'll be notified within the app. Other than that, we'll let you know through Facebook and/or Twitter."; ?>&lt;/p>
            &lt;/article>

Method #2 : 
&lt;article id="update">
                &lt;h2><?php echo ('faq-update-title'); ?>&lt;/h2>
                &lt;p><?php echo ('faq-update-content'); ?>&lt;/p>
            &lt;/article>

**Comment by phnz** [comment]
I suggest method #1 we can make it dynamic and new content will be automatically pushed to poeditor with the api.

Something like that: `<?php echo _("Watch torrent movies instantly"); ?>`

**Comment by Coleyra** [comment]
So, if the english sentence is changed, what will happen ?

**Comment by phnz** [comment]
You got a good point. What you think using method #2 hehe

**Comment by phnz** [comment]
But I think it'll be easier to manage with method #1 but I think method #2 will be more "clean". As we don't have a lot of translation to import

**Comment by Coleyra** [comment]
I'm ok for Method #2 but we need a standard for this :)

Something like :
pagename-category-element ?

**Comment by Coleyra** [comment]
I'll try to do it tomorrow, with english / french.

**Comment by phnz** [comment]
pagename-category-element that make sense to me.

can i have your email i'll add you admin of the project on poeditor 
you can send it to phnz @ freenode

thanks

**Comment by SrPatinhas** [comment]
@Coleyra  and @phenomenz  i think, the #2 method is better, cleanner and easier, i can do portuguese version

**Comment by phnz** [comment]
@Coleyra @sharkiller 

Guys can you coordinate I think @sharkiller already works on something about it.

Thanks

**Comment by sharkiller** [comment]
translation is done in the other branch. langs are in /lang/
only the select menu is missing until we have a good amount of translations.

**Comment by SrPatinhas** [comment]
i will translate to portuguese then, and maybe for other language if its necessary

**Comment by sharkiller** [comment]
@SrPatinhas the file going to be uploaded to getlocalization for consistency. and easy maintenance.

**Comment by SrPatinhas** [comment]
@sharkiller i just finnish the translation, if you need something more just tell me ;)

**Comment by Coleyra** [comment]
@sharkiller It will be in the same getlocalization project ?

**Comment by Coleyra** [comment]
The index.php contain all the method to get the language, but if we want to do it on other pages we need to place this code in a separate file.
Are we placing it in a new directory, and what will be the name of the file ?

include/essential.php

inc/getLanguage.php

function/main.php

./header.php

other ?

**Comment by PatruSorin** [comment]
I can do the translation in romanian if you need it

**Comment by SrPatinhas** [comment]
@PatruSorin  yes, how many more languages ​​better, so if they need anything do not need to see in other languages than maternal.

@Coleyra and @sharkiller i still do not quite understand how this works and that :S some of you will be able to explain if you give me please?

And another point, much as, for example I'm Portuguese and I live in Portugal, to have the site translated into Portuguese because the IP from where I am (do not know if and how it works) could for example be in France or in another country Portuguese and wanting the same, this is a point that I say, you can not have so much importance and do not be the most.

sorry if it's not this, just have not figured it well

**Comment by Coleyra** [comment]
For now we are just using a parameter in the url to set the language, something like => get-popcorn.com/?lang=pt
Maybe in the future we can use IP detection or subdomains for other languages like => pt.get-popcorn.com or get-popcorn.com/pt

**Comment by PatruSorin** [comment]
@SrPatinhas Yes romanian is my first language but where should I post the translation after it is done?

**Comment by SrPatinhas** [comment]
@PatruSorin go to https://github.com/popcorn-official/popcorn-site/tree/multilang-phptest/lang and make a pull request and translate the text there, i made a pt.php in my fork

**Comment by remil19** [comment]
Some already done a lot of work to translate the previous site (which was very similar). Go check https://github.com/remil19/popcorn-time.github.io

It's very easy : changes are made in dev/index.php and languages/*.json and the whole site is generated automatically.

**Comment by sharkiller** [comment]
english master added to: http://www.getlocalization.com/PopcornTime/
go there for translations
