### ISSUE TITLE
wrong platform recommendation and download button not working

### ISSUE THREAD

**Issue by vmussa** [popcorn-official/popcorn-site-legacy#45]
I'm using Windows 7 right now, but the site is recommending me the Mac version.
Also, when I click "other platforms" and try to download the windows version through clicking the download button nothing happens.
Is it only me? It is happening in both Firefox and Chrome.

**Comment by frdmn** [comment]
This issue is related to AdBlock. Disable it and try again, please.

**Comment by vmussa** [comment]
I see. I would like just to say that now I'm in Ubuntu/Firefox with AdBlock Plus and the site is working normally.

**Comment by krizzmp** [comment]
i had the same issue on linux, where it showed the mac version but after a refresh it worked. and im not using adblock

**Comment by ghost** [comment]
It was probably a Javascript issue.
