### ISSUE TITLE
Website translation

### ISSUE THREAD

**Issue by hadim** [popcorn-official/popcorn-site-legacy#48]
I think it could be great to have the website translated to many languages since PT is already translated.

It will improve SEO and PT will have a better visiblity to "basic user".

I quickly see that content is hardcoded in html and js file so I don't know  how hard it will be to allow translation.

Do you think website translation could be good ?

If so, what is the best way to do it ?

**Comment by TixieSalander** [comment]
Yey, want it !

**Comment by hadim** [comment]
Any news here?

**Comment by ValentinCreative** [comment]
Hi, 
I saw "data-i18n" properties in html, so I suppose it's for http://i18next.com/
But i doesn't see any i18next js in the sources.

**Comment by ValentinCreative** [comment]
I didn't see, there is a i18next from CDN.
But it's apparently not initialized.

**Comment by se-bastiaan** [comment]
Done
