### ISSUE TITLE
website with app on it ..

### ISSUE THREAD

**Issue by Draxler** [popcorn-official/popcorn-site-legacy#52]
I know copyright issue with posters is behind the reason why there is no app on the website. But what if you guys put app on the website with out movie posters and you use ''empty posters''.. I strongley bealive app should be on the main website and this could be solution to this copyright problems.. 
Something like this ( this one is not done in quality, it's just to show what i mean.  you guys could do this in quality)

![new screen1](https://cloud.githubusercontent.com/assets/7681671/3145877/3332b7ca-ea3e-11e3-835a-77bf4be33491.PNG)

( I put this here because i see this as an issue )
Regards

**Comment by Draxler** [comment]
Maybe every second poster could have Popcorn in it instead of TV icon. 
(Popcorn icon Like one in the midle on this screenshout, maybe litlle smaller then this one the screenshot, it should be in same size like TV icon is)

**Comment by ghost** [comment]
@Draxler There is no point putting something that doesn't represent the app on the website.

**Comment by SlashmanX** [comment]
Or we should just show non-copyrighted movies like the original PT

**Comment by Draxler** [comment]
@xeoncore 
TV icon in the midle of ''empty poster'' represent movies or whatever could be played on TV. And it's croucial to show UI (design) and app it self .. And app it self represent the app.. imo, anyway.
Every alternative to P.T. show on their websites app it self . These ''empty posters'' could be the answer (solution) to copy right question. Or something like @SlashmanX said, to do a litlle reserch and find movie posters wich are in Public Domain and make sure there is no copy right holder behind it..

**Comment by ghost** [comment]
@Draxler The covers are not a copyright issue. Trakt.tv supplies us with the covers and they also show them on their site, does this mean they are breaking copyright too?

**Comment by SlashmanX** [comment]
The covers are a copyright issue, at least when displaying them as advertising functionality on the website. There's a reason the original PT team used non-copyrighted movies in the screenshots

**Comment by ghost** [comment]
@SlashmanX And that wasn't the reason.

**Comment by SlashmanX** [comment]
What was the reason?

**Comment by ghost** [comment]
@SlashmanX Everytime people get redirected to one of those sites that advertises "Watch Free Movies" they always attract people with good looking stuff that doesn't exist. Using movies, but movies that aren't popular actually reduces peoples suspicion.

**Comment by Draxler** [comment]
@xeoncore 
I followed disqussion on P.T. forum and if i'm not mistaken someone propose to use app on the website and at that time it was said that copy right problems is the main reason behind it why there is no app on the website..

**Comment by SlashmanX** [comment]
No it's because those movies that were shown had no copyright anymore, so the PT weren't advertising "pirating", just watching non-copyrighted movies

**Comment by ghost** [comment]
@SlashmanX Whatever you say ^^

**Comment by summersz** [comment]
You wouldn't be infringing copyright for just showing film posters I guess but you would be actively advertising being able to watch copyrighted material through PT, that's definitely not a good thing.  
What about something like this? Keep everyone happy.
![example](https://cloud.githubusercontent.com/assets/7293216/3209262/d6f76558-ee63-11e3-90cc-214354ba672c.png)

**Comment by ghost** [comment]
@summersz I agree with you there. We are trying to steer Popcorn Time away from being a "copyright infringing program" by implementing plugins, where we wouldn't package the YTS/EZTV plugin directly with the software.

**Comment by yoeluru** [comment]
I'm very lost right now, is there another place where the source code is located at? i can not find anything.
Look, If github doesn't want the code here, fine, some other place then, but has to be fast or else the community of popcorn would be spread out. Why don't you create a forum inside the popcorntime.io site? maybe then we can all be in touch.

**Comment by SlashmanX** [comment]
We have a forum inside popcorntime.io. It's just down atm.

It takes a long time to migrate all the code and issues to a new privately hosted repo but we're on top of it and you should see something soon

**Comment by yoeluru** [comment]
the forum has been down a week now, really nothing more?

**Comment by hadim** [comment]
Same here? Any news about PPT source code and also about http://discuss.popcorntime.io/ ?

**Comment by ghost** [comment]
Its back online.
