### ISSUE TITLE
Is https belong to official Popcorn Time ?

### ISSUE THREAD

**Issue by Draxler** [popcorn-official/popcorn-site-legacy#59]
i noticed that Popcorn Time website is now reachable also trough HTTPS . 
I want to know if this https://popcorntime.io/ belong to official Popcorn Time or should i use only HTTP (http://popcorntime.io) ..

**Comment by SlashmanX** [comment]
Yes, it belongs to us

**Comment by Draxler** [comment]
great,  thanx ..
