### ISSUE TITLE
Popcorn/Trakt.tv

### ISSUE THREAD

**Issue by ghost** [popcorn-official/popcorn-site-legacy#72]
When i put my account on that space to get the 'automatically scrobble episodes' thing, it appears the loading icon, and then i get a red cross, saying that is not synced. I made my account on Trakt.tv without using a social net.. I don't know if is problem os an update or something wrong with the plug-in, somebody give me any advice or tip whatever please! and thanks! (:

**Comment by se-bastiaan** [comment]
This is not the place to report issues with our desktop application. You can do that here: http;//git.popcorntime.io/jira

But I'll answer your question anyways: the Trakt API changed and the syncing will not work until we release a new version of the application. But implementing the new code takes time, so it can take a while.
